### ISSUE TITLE
L'app Java CieID lancia eccezione java.awt.AWTError

### ISSUE THREAD

**Issue by tappoz** [italia/cie-middleware-linux#59]
Su Ubuntu 22.04 (pacchetto `.deb` del middleware) il file di configurazione per Java 1.8 `/etc/java-8-openjdk/accessibility.properties` non deve contenere la property `assistive_technologies=org.GNOME.Accessibility.AtkWrapper` altrimenti l'applicazione CieID:

- fallisce in silenzio quando lanciata cliccando sull'icona configurata qui `/usr/share/applications/cieid.desktop`
- fa vedere questa stacktrace quando lanciata da terminale con il comando dentro a `/usr/share/applications/cieid.desktop`.

```
$ java -Xms1G -Xmx1G -Djna.library.path=".:/usr/local/lib" -classpath "/usr/share/CIEID/cieid.jar" it.ipzs.cieid.MainApplication
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at it.ipzs.cieid.MainApplication.main(MainApplication.java:27)
```

L'applicazione CieID dovrebbe fornire questo contesto qui sopra :point_up: anche quando avviata cliccando sull'icona, altrimenti diventa davvero difficile capire cosa non sta funzionando.

Per maggior contesto: https://forum.italia.it/t/ubuntu-22-04/31773/43

**Comment by aantetomaso** [comment]
Risolta nella 1.4.3.9
