### ISSUE TITLE
L'app CieID non funziona se /tmp è montata con l'opzione 'noexec'

### ISSUE THREAD

**Issue by henrythebuilder** [italia/cie-middleware-linux#77]
Salve,
l'applicazione CieID non funziona se `/tmp` è montata con l'opzione '**noexec**'.
Ogni operazione rimane '_appesa_' senza esito.
Rimuovendo questa opzione l'applicazione funziona correttamente per firma (cades, pades e pades+firma grafica) e verifica.

sistema di riferimento:
```
Host: Dell System XPS
OS: Debian GNU/Linux 12 (bookworm) x86_64
Debian version: 12.5
Kernel: 6.7.12+bpo-amd64 
CIE-Middleware: 1.4.3-7.amd64
Lettore usb: miniLector AIR 3 (bit4id)
Driver usb: bit4id-ccid-amd64.3.1.1-567
```

Log errore:
```
...
TabbedPan Selected Index: 12
TabbedPan Selected Index: 14
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: Could not initialize class it.ipzs.cieid.Middleware
        at it.ipzs.cieid.MainFrame.signMWCall(MainFrame.java:3073)
        at it.ipzs.cieid.MainFrame.access$115(MainFrame.java:3012)
        at it.ipzs.cieid.MainFrame$71.run(MainFrame.java:3007)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/jna--1220869536/jna16114988032639615485.tmp: /tmp/jna--1220869536/jna16114988032639615485.tmp: mappatura del segmento dall'oggetto condiviso non riuscita [in thread "Thread-0"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1957)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
        at com.sun.jna.Native.<clinit>(Native.java:131)
        at it.ipzs.cieid.Middleware.<clinit>(Middleware.java:13)
        at it.ipzs.cieid.MainFrame$38$1.run(MainFrame.java:1511)
        ... 1 more

```
Saluti
Enrico

**Comment by spaccabits** [comment]
confermo anche per Debian 13.5, kernel 7.0.10-1~bpo13+1
CIE-Middleware-1.4.3-12.amd64
stesso lettore con drive da repository (libacsccid.so)

francamente mi sembra una ... cosa piuttosto seria influendo pesantemente sulla sicurezza del sistema

c'è da aggiungere che con ACR122U dà errore comunque
